# Starts everything except the databus
version: "3.0"
services:
  moss-client:
    image: dbpedia/databus-moss-client:dev
    container_name: moss_client
    environment:
      VITE_MOSS_BASE_URL: http://moss-server:8080
    ports:
      - "5000:5173"
  moss-server:
    image: dbpedia/databus-moss-server:dev
    container_name: moss_server
    environment:
      CONFIG_PATH: /config/moss-config.yml
      LOOKUP_BASE_URL: http://lookup:8082
      GSTORE_BASE_URL: http://gstore:8080
      USER_DATABASE_PATH: /users/user.db
    volumes:
      - "./data/users:/users"
      - "./config:/config"
    ports:
      - "5001:8080"
  lookup:
    image: dbpedia/lookup:dev
    container_name: moss_lookup
    ports:
      - "5002:8082"
    volumes:
      - "./config/lookup-config.yml:/resources/config.yml"
      - "./data/index:/index"
  gstore:
    image: dbpedia/gstore:rogue-jan
    container_name: moss_gstore
    environment:
      STORAGE_USER: "dba"
      STORAGE_PASS: "everyoneknows"
      STORAGE_SPARQL_ENDPOINT_URI: http://virtuoso:8890/sparql
      GSTORE_LOCALHOST_CONTEXT_FALLBACK_URL: http://172.17.0.1
    ports:
      - "5003:8080"
    volumes:
      - ./data/gstore/git:/gstore/git
      - ./data/gstore/logs:/gstore/logs
  virtuoso:
    image: "openlink/virtuoso-opensource-7:latest"
    container_name: moss_virtuoso
    environment:
      DBA_PASSWORD: "everyoneknows"
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://localhost:2000"
    ports:
      - "5004:8890"
    volumes:
      - ./data/virtuoso:/database
    entrypoint: /bin/bash -c "
        echo 'grant SPARQL_LOAD_SERVICE_DATA to \"SPARQL\";' > /opt/virtuoso-opensource/initdb.d/ini.sql &&
        echo 'grant SPARQL_SPONGE to \"SPARQL\";' >> /opt/virtuoso-opensource/initdb.d/ini.sql &&
        echo 'grant SPARQL_SELECT_FED to \"SPARQL\";' > /opt/virtuoso-opensource/initdb.d/ini.sql &&
        /virtuoso-entrypoint.sh
      "
