version: "3.0"
services:
  # Frontend Svelte App for HTML view, login and API-key creation
  moss-frontend:
    image: dbpedia/databus-moss-client:dev
    container_name: moss_dev_frontend
    environment:
      PUBLIC_MOSS_BASE_URL: https://dev.moss.dbpedia.org
      ORIGIN: https://dev.moss.dbpedia.org
      AUTH_OIDC_CLIENT_ID: moss-dev
      AUTH_OIDC_CLIENT_SECRET: z7feqbX7lGyAFzPzGIaC4LT7vidPqrP5
      AUTH_OIDC_ISSUER: https://auth.dbpedia.org/realms/dbpedia
      AUTH_OIDC_CLIENT_SCOPE: "openid profile email"
    ports:
      - "5000:3000"
  # MOSS Server
  moss-server:
    image: dbpedia/databus-moss-server:dev
    container_name: moss_dev_server
    environment:
      USER_DATABASE_PATH: /users/users.db
      CONFIG_PATH: /config/moss-config.yml
      LOOKUP_BASE_URL: http://lookup:8082
      GSTORE_BASE_URL: http://gstore:8080
      MOSS_BASE_URL: https://dev.moss.dbpedia.org
    volumes:
      - "./config:/config"
      - "./data/users:/users"
    ports:
      - "5001:8080"
  # Lookup for indexed search
  lookup:
    image: dbpedia/lookup:dev
    container_name: moss_dev_lookup
    ports:
      - "5002:8082"
    volumes:
      - "./config/lookup-config.yml:/resources/config.yml"
      - "./index:/index"
  gstore:
    image: dbpedia/gstore:dev
    container_name: moss_dev_gstore
    environment:
      STORAGE_USER: "dba"
      STORAGE_PASS: "everyoneknows"
      STORAGE_SPARQL_ENDPOINT_URI: http://virtuoso:8890/sparql
      GSTORE_LOCALHOST_CONTEXT_FALLBACK_URL: http://172.17.0.1
    ports:
      - "5003:8080"
    volumes:
      - ./data/gstore/git:/gstore/git
      - ./data/gstore/logs:/gstore/logs
  virtuoso:
    image: "openlink/virtuoso-opensource-7:latest"
    container_name: moss_dev_virtuoso
    environment:
      DBA_PASSWORD: "everyoneknows"
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://localhost:2000"
    ports:
      - "5004:8890"
    volumes:
      - ./data/virtuoso:/database
    entrypoint: /bin/bash -c "
        echo 'grant SPARQL_LOAD_SERVICE_DATA to \"SPARQL\";' > /opt/virtuoso-opensource/initdb.d/ini.sql &&
        echo 'grant SPARQL_SPONGE to \"SPARQL\";' >> /opt/virtuoso-opensource/initdb.d/ini.sql &&
        echo 'grant SPARQL_SELECT_FED to \"SPARQL\";' > /opt/virtuoso-opensource/initdb.d/ini.sql &&
        /virtuoso-entrypoint.sh
      "
