version: "1.0"
indexMode: INDEX_SPARQL_ENDPOINT
sparqlEndpoint: http://virtuoso:8890/sparql
indexFields:
  - fieldName: annotatedCount
    documentVariable: oeoClass
    type: numeric
    query: >
      SELECT ?oeoClass (COUNT(DISTINCT ?layer) as ?annotatedCount) WHERE {
        {
          GRAPH ?g {
            ?layer a <http://dataid.dbpedia.org/ns/moss#DatabusMetadataLayer> .
            ?s <https://saref.etsi.org/core/isAbout> ?oeoClass .
          }
        } 
        UNION 
        {
          GRAPH ?g {
            ?layer a <http://dataid.dbpedia.org/ns/moss#DatabusMetadataLayer> .
            ?_ <http://purl.org/dc/elements/1.1/subject> ?oeoClass .
          } 
        }

        ?oeoClass <http://www.w3.org/2000/01/rdf-schema#label> ?label .
        ?oeoClass a <http://www.w3.org/2002/07/owl#Class> .
      } GROUP BY ?oeoClass
