version: "1.0"
indexMode: INDEX_SPARQL_ENDPOINT
sparqlEndpoint: http://virtuoso:8890/sparql
indexFields:
  - fieldName: annotation
    documentVariable: mod
    type: uri
    query: >
      SELECT DISTINCT ?mod ?annotation WHERE {
          GRAPH ?g {
            ?mod a <http://dataid.dbpedia.org/ns/moss#DatabusMetadataLayer> .
            ?_ <http://purl.org/dc/elements/1.1/subject> ?annotation .
          }
          #VALUES#
      }
  - fieldName: used
    documentVariable: mod
    type: uri
    query: >
      SELECT DISTINCT ?mod ?used WHERE {
          GRAPH ?g {
            ?mod a <http://dataid.dbpedia.org/ns/moss#DatabusMetadataLayer> .
            ?mod <http://www.w3.org/ns/prov#used> ?used .
          }
          #VALUES#
      }
