version: "1.0"
indexPath: ./index
maxBufferedDocs: 1000000
logInterval: 10000
exactMatchBoost: 6
prefixMatchBoost: 5
fuzzyMatchBoost: 2
fuzzyEditDistance: 2
fuzzyPrefixLength: 2
boostFormula: 1 + 0.1 * ln(annotatedCount + 1)
maxResults: 1000
format: JSON
minScore: 0.1
lookupFields:
  - name: id
    weight: 10
    exact: true
    tokenize: false
    required: true
    highlight: false
    queryByDefault: false
  - name: label
    weight: 10
    highlight: true
    tokenize: true
    queryByDefault: true
    allowPartialMatch: true
    required: false
    exact: false
  - name: annotatedCount
    type: numeric
    weight: 1
  - name: annotation
    type: uri
    tokenize: false
    weight: 1
  - name: used
    type: uri
    weight: 1
    tokenize: false
