loaders:
  - collectionURI: https://databus.dbpedia.org/janfo/collections/moss-ontologies
    indexer:
      configPath: ./indexers/ontology-indexer.yml
layers:
  - name: simple
    templatePath: layers/simple/template.jsonld
    shaclPath: layers/simple/shapes.shacl
    scope: version
    indexers:
      - layers/simple/indexer.yml
      - indexers/annotate-count-indexer.yml
  - name: openenergy
    templatePath: layers/openenergy/template.jsonld
    shaclPath: layers/openenergy/shapes.shacl
    scope: version
    indexers:
      - layers/openenergy/indexer.yml
      - indexers/annotate-count-indexer.yml
  - name: opentransport
    templatePath: layers/opentransport/template.jsonld
    shaclPath: layers/opentransport/shapes.shacl
    scope: version
    indexers:
      - layers/opentransport/indexer.yml
      - indexers/annotate-count-indexer.yml