layers:
  - name: simple
    template: layers/simple/template.ttl
  - name: oemetadata
    template: layers/openenergy/template.jsonld
  - name: opentransport
    template: layers/opentransport/template.jsonld
loaders:
  - collectionURI: https://databus.dbpedia.org/janfo/collections/moss-ontologies
    indexer:
      configPath: ./common/ontology-indexer.yml
indexers:
  - configPath: ./layers/simple/indexer.yml
    layers:
      - simple
  - configPath: ./layers/openenergy/indexer.yml
    layers:
      - oemetadata
  - configPath: ./layers/opentransport/indexer.yml
    layers:
      - opentransport
  - configPath: ./common/annotate-count-indexer.yml
    layers:
      - oemetadata
      - simple