version: "1.0"
indexMode: INDEX_SPARQL_ENDPOINT
sparqlEndpoint: http://virtuoso:8890/sparql
indexFields:
  - fieldName: annotation
    documentVariable: layer
    type: uri
    query: >
      SELECT DISTINCT ?layer ?annotation WHERE {
        GRAPH ?g {
          ?layer a <http://dataid.dbpedia.org/ns/moss#DatabusMetadataLayer> .
          ?layer <http://dataid.dbpedia.org/ns/moss#layerName> "openenergy" .
          ?layer <http://dataid.dbpedia.org/ns/moss#content> ?content .
        }
        GRAPH ?content {
          {
            ?_ <https://saref.etsi.org/core/isAbout> ?annotation .
            FILTER (strstarts(str(?annotation), 'http://openenergy-platform.org/ontology/oeo/OEO_'))
          }
          UNION
          {
            ?_ <http://purl.org/dc/elements/1.1/subject> ?annotation .
            FILTER (strstarts(str(?annotation), 'http://openenergy-platform.org/ontology/oeo/OEO_'))
          }
        }
        #VALUES#
      }
