version: "1.0"
indexMode: INDEX_SPARQL_ENDPOINT
sparqlEndpoint: http://virtuoso:8890/sparql
indexFields:
  - fieldName: label
    documentVariable: class
    query: >
      SELECT ?class ?label WHERE {
        {
          ?class a <http://www.w3.org/2002/07/owl#Class> .
          ?class <http://www.w3.org/2000/01/rdf-schema#label> ?label .
          FILTER(lang(?label) = 'en')
        }
      }
  - fieldName: type
    documentVariable: class
    query: >
      SELECT ?class ?type WHERE {
        {
          ?class a <http://www.w3.org/2002/07/owl#Class> .
          BIND("class" AS ?type)
        }
      } 
  
        
